# Generated by Django 5.2.14 on 2026-08-05 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS Text'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sms', help_text='Channel through which the message was received.', max_length=20)),
                ('raw_text', models.TextField(help_text='Original raw body text of the message.')),
                ('sender', models.CharField(blank=True, help_text='Phone number, email address, or sender ID.', max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted this message for detection (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['submitted_at'], name='inbox_messa_submitt_dc073a_idx'), models.Index(fields=['channel'], name='inbox_messa_channel_9fb16d_idx'), models.Index(fields=['sender'], name='inbox_messa_sender_f03da4_idx')],
            },
        ),
    ]
