# Generated by Django 5.2.14 on 2026-08-05 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('legit', 'Legitimate'), ('spam', 'Spam'), ('fraud', 'Fraud / Phishing')], db_index=True, default='legit', help_text='Threat classification label.', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score from 0.0 to 1.0.')),
                ('flagged_keywords', models.JSONField(blank=True, default=list, help_text='List of flagged keywords or suspicious tokens extracted.')),
                ('language_mix', models.CharField(choices=[('english', 'English'), ('pidgin', 'Nigerian Pidgin'), ('mixed', 'Mixed Language')], default='english', help_text='Primary language mixture of the message.', max_length=30)),
                ('model_version', models.CharField(default='v1.0', help_text='Version of ML/heuristic model used.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.OneToOneField(help_text='Associated message inspected by detector.', on_delete=django.db.models.deletion.CASCADE, related_name='detection_result', to='inbox.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_label', models.CharField(choices=[('legit', 'Legitimate'), ('spam', 'Spam'), ('fraud', 'Fraud / Phishing')], help_text='User-suggested correct label for model retraining.', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Reasoning or notes to assist model retraining.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('corrected_by', models.ForeignKey(blank=True, help_text='User submitting the feedback correction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_corrections', to=settings.AUTH_USER_MODEL)),
                ('detection_result', models.ForeignKey(help_text='Target detection result being flagged or corrected.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_corrections', to='detector.detectionresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['label'], name='detector_de_label_13b036_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['created_at'], name='detector_de_created_f41c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['confidence_score'], name='detector_de_confide_36facf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcorrection',
            index=models.Index(fields=['created_at'], name='detector_fe_created_069db6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcorrection',
            index=models.Index(fields=['corrected_label'], name='detector_fe_correct_18e0d3_idx'),
        ),
    ]
